// Generated by CoffeeScript 1.3.3
(function() {
  var Bullet,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bullet = (function(_super) {

    __extends(Bullet, _super);

    function Bullet(x, y, radius, x_velocity, y_velocity) {
      if (radius == null) {
        radius = 3;
      }
      Bullet.__super__.constructor.call(this, x, y, radius, x_velocity, y_velocity, 'yellow', 'black');
    }

    Bullet.prototype.draw = function() {
      return Bullet.__super__.draw.call(this, true, true);
    };

    return Bullet;

  })(CircleMovingInGameObject);

}).call(this);
