// Generated by CoffeeScript 1.3.3
(function() {
  var Explosion,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Explosion = (function(_super) {

    __extends(Explosion, _super);

    function Explosion(ex_circle) {
      Explosion.__super__.constructor.call(this, ex_circle.cx, ex_circle.cy, ex_circle.radius, 0, 0, ex_circle.fill_style, ex_circle.stroke_style);
    }

    Explosion.prototype.update = function() {
      if (this.fill_style.a) {
        this.fill_style.a = this.fill_style.a - 0.05;
        if (this.fill_style.a <= 0) {
          this.active = false;
        }
      }
      return this.radius = this.radius + 10;
    };

    Explosion.prototype.draw = function() {
      return Explosion.__super__.draw.call(this, true, true);
    };

    return Explosion;

  })(CircleMovingInGameObject);

}).call(this);
