// Generated by CoffeeScript 1.3.3
(function() {
  var start;

  $('#gamearea').append(game_element);

  console.log(player1);

  start = function() {
    var bullets, enemies, explosions, player1;
    enemies = [];
    bullets = [];
    explosions = [];
    return player1 = new Player(CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2, 20);
  };

  start();

  runtime();

}).call(this);
